### PR TITLE
Do not allow dedicated regions to be marked primary

### LINKED ISSUE #113: Provider produced inconsistent result after apply
Received an error after applying, although the cluster itself was actually created. 
```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.cockroachdb_dedicated.cockroach_cluster.cluster, provider "provider[\"registry.terraform.io/cockroachdb/cockroach\"]" produced an
│ unexpected new value: .regions[0].primary: was cty.True, but now cty.False.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

Running a plan after this forced a recreation of the cluster
```

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.cockroachdb_dedicated.cockroach_cluster.cluster is tainted, so must be replaced
```

Terraform code
```terraform
resource "cockroach_cluster" "cluster" {
  cloud_provider = "AWS"
  name           = "test"
  regions = [
    {
      name       = "ap-southeast-1"
      node_count = 3
      primary = true
    }
  ]

  dedicated = {
    num_virtual_cpus           = 2
    storage_gib                = 100
    private_network_visibility = true
  }

}
```

Terraform versions
```
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/cockroachdb/cockroach v0.4.7
+ provider registry.terraform.io/hashicorp/aws v4.66.1
```

### PR DESCRIPTION
**Pull request by pjtatlow**
If a dedicated cluster has a primary region, the plan that's created doesn't match the state of the cluster. This change creates an error if a dedicated cluster's region is marked as primary, and adds some documentation to specify that only serverless regions should me marked primary.

Fixes #113

### CODE REVIEW

File: internal/provider/cluster_resource.go [hunk 1]
```diff
@@ -315,6 +316,10 @@ func (r *clusterResource) Create(
 		if plan.Regions != nil {
 			regionNodes := make(map[string]int32, len(plan.Regions))
 			for _, region := range plan.Regions {
+				if region.Primary.ValueBool() {
```
Comment (erademacher) [inline internal/provider/cluster_resource.go:319]: You can actually do this validation at plan time in `ConfigValidators` instead. I think something like this should work:
```
resourcevalidator.Conflicting(
	path.MatchRoot("regions").AtAnyListIndex().AtName("primary"),
	path.MatchRoot("dedicated"),
),
```

**Review by erademacher — CHANGES_REQUESTED** [review]

File: internal/provider/cluster_resource.go (hunk 1 above)
Comment (pjtatlow) [reply internal/provider/cluster_resource.go]: Done!

**Review by erademacher — APPROVED** [review]
Beautiful. Thanks PJ!

**Comment by jaylim-crl** [comment]
I believe this PR breaks serverless cluster creation:

```bash
$ terraform plan
╷
│ Error: Invalid Attribute Combination
│
│   with cockroach_cluster.serverless,
│   on x.tf line 12, in resource "cockroach_cluster" "serverless":
│   12: resource "cockroach_cluster" "serverless" {
│
│ These attributes cannot be configured together: [regions[*].primary,dedicated]
╵
```

```tf
resource "cockroach_cluster" "serverless" {
  name           = "foo-123"
  cloud_provider = "AWS"
  serverless = {
      spend_limit = 0
  }
  regions = [
    {
      name = "us-east-1"
      primary = false
    },
    {
      name  = "eu-central-1"
      primary = true
    },
  ]
}
```

I suspect the conflict validator doesn't account for null values. Setting dedicated to `null` when specifying a primary region should be allowed.

**Comment by jaylim-crl** [comment]
It appears that the following should work:

```go
resourcevalidator.Conflicting(
	path.MatchRoot("regions").AtAnyListIndex().AtName("primary"),
	path.MatchRoot("dedicated"),
),
```

Hm, not sure why that doesn't work as intended.

**Comment by jaylim-crl** [comment]
I see. This worked:

```tf
resource "cockroach_cluster" "serverless" {
  name           = "foo-123"
  cloud_provider = "AWS"
  serverless = {
      spend_limit = 0
  }
  regions = [
    {
      name = "us-east-1"
      primary = false
    },
    {
      name  = "eu-central-1"
    },
  ]
}
```

But not:

```tf
resource "cockroach_cluster" "serverless" {
  name           = "foo-123"
  cloud_provider = "AWS"
  serverless = {
      spend_limit = 0
  }
  regions = [
    {
      name = "us-east-1"
      primary = false
    },
    {
      name  = "eu-central-1"
      primary = true
    },
  ]
}
```

I think if we tried to set `primary` on more than one regions, it would error out with the conflict error.
